# Generated by Django 4.0.2 on 2022-02-06 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('warehouse', models.IntegerField(editable=False, verbose_name='ID User')),
                ('status', models.IntegerField(choices=[(1, 'Created'), (2, 'Accepted'), (3, 'Being formed'), (4, 'Awaiting shipment'), (5, 'Shipped'), (6, 'Waiting at the pick-up point'), (7, 'Completed')], verbose_name='Status order')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
    ]
