# Generated by Django 4.0.2 on 2022-02-06 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_order_date_edit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_edit',
            field=models.DateTimeField(auto_now=True, verbose_name='Time last edit'),
        ),
    ]
