# Generated by Django 4.0.2 on 2022-02-06 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_order_date_edit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='date_edit',
        ),
    ]
