# Generated by Django 4.0.2 on 2022-02-05 05:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('status', models.IntegerField(choices=[(1, 'Created'), (2, 'Accepted'), (3, 'Being formed'), (4, 'Awaiting shipment'), (5, 'Shipped'), (6, 'Waiting at the pick-up point'), (7, 'Completed')], verbose_name='Status order')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='warehouse')),
            ],
        ),
    ]
