# Generated by Django 4.0.2 on 2022-02-05 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_user_alter_order_warehouse'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
