# Generated by Django 4.0.2 on 2022-02-06 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_order_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-id'], 'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
    ]
