# Generated by Django 4.0.2 on 2022-02-06 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_order_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date_edit',
            field=models.DateTimeField(auto_now=True, verbose_name='Time last edit'),
        ),
    ]
